export default {
  $window: window,
  $document: document,
  $html: document.documentElement,
  $body: document.body,
  $bannerSlider: document.querySelector('.banner-slider'),
  $catalogSlider: document.querySelector('.hero-catalog__slider'),
  $catalogFiltersTop: document.querySelectorAll('.catalog-filter__top'),
  $hideFilters: document.querySelector('.hide-filters'),
  $catalogColumns: document.querySelector('.catalog-columns__list'),
  $catalogGridContent: document.querySelector('.catalog-grid__content'),
  $catalogFilterItems: document.querySelectorAll('.catalog-filter__item'),
  $catalogChoice: document.querySelector('.catalog-choice'),
  $customSelect: document.querySelectorAll('.custom-select'),
  $colorSelect: document.querySelector('.color-select'),
  $stepper: document.querySelector('.stepper'),
  $cardSliderThumbs: document.querySelector('.card-slider__thumbs'),
  $sliderImg: document.querySelector('.card-slider__main img'),
  $cardDescrLink: document.querySelectorAll('.card-description__link'),
  $cardRelatedSlider: document.querySelector('.card-related__slider'),
  $buyButtons: document.querySelectorAll('.product__button'),
  $cartCounter: document.querySelector('.icon__quantity'),
  $cartButtons: document.querySelectorAll('.card-info__btn--tocart'),
  $cart: document.querySelector('.cart'),
  $fullPrice: document.querySelector('.cart__price'),
  $cartProductsList: document.querySelectorAll('.cart__items'),
  $catalogFilters: document.querySelector('.catalog-filters'),
}
